const items = [
	{ imageUrl: "/projects/product_12.jpeg" },
	{ imageUrl: "/projects/product_13.jpeg" },
	{ imageUrl: "/projects/product_14.jpeg" },
	{ imageUrl: "/projects/product_15.jpeg" },
	{ imageUrl: "/projects/product_16.jpeg" },
	{ imageUrl: "/projects/product_17.jpeg" },
	{ imageUrl: "/projects/product_18.jpeg" },
	{ imageUrl: "/projects/product_19.jpeg" },
	{ imageUrl: "/projects/product_1.jpeg" },
	{ imageUrl: "/projects/product_2.jpeg" },
	{ imageUrl: "/projects/product_3.jpeg" },
	{ imageUrl: "/projects/product_4.jpeg" },
	{ imageUrl: "/projects/product_5.jpeg" },
	{ imageUrl: "/projects/product_7.jpeg" },
	{ imageUrl: "/projects/product_8.jpeg" },
	{ imageUrl: "/projects/product_9.jpeg" },
	{ imageUrl: "/projects/product_10.jpeg" },
	{ imageUrl: "/projects/product_11.jpeg" },
	{ imageUrl: "/projects/product_20.jpeg" },
	{ imageUrl: "/projects/product_21.jpeg" },
	{ imageUrl: "/projects/product_22.jpeg" },
	{ imageUrl: "/projects/product_23.jpeg" },
	{ imageUrl: "/projects/product_24.jpeg" },
	{ imageUrl: "/projects/product_25.jpeg" },
	{ imageUrl: "/projects/product_26.jpeg" },
	{ imageUrl: "/projects/product_27.jpeg" },
	{ imageUrl: "/projects/product_28.jpeg" },
	{ imageUrl: "/projects/product_29.jpeg" },
	{ imageUrl: "/projects/product_30.jpeg" },
];

export default items;
