import Head from "next/head";
import Image from "next/image";
import Nav from "../components/nav/Nav";

export default function Home() {
	return (
		<div className="font-Poppins">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="">
				<Nav />
				<section className="max-w-[90%] md:max-w-[80%] mx-auto">
					<div>
						<h1 className="text-5xl font-bold">
							Architecture that recognizes all your sensibilities
						</h1>
						<h3>
							Welcome to Anisarp a reliable business partner on your path to
							building a better looking future for all
						</h3>
					</div>
				</section>
			</main>
			<footer>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
